# Generated by Django 3.0.3 on 2020-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='descricao',
            field=models.CharField(default='Dê uma olhada também', max_length=200),
        ),
    ]
