# Generated by Django 3.0.3 on 2020-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_subcategoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(default='Venha conferir nossos produtos na Categoria <django.db.models.fields.CharField>', max_length=200),
        ),
    ]
