# Generated by Django 3.0.3 on 2020-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20200211_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, default='media/produtos/imagens/produto.png', null=True, upload_to='produtos/imagens'),
        ),
    ]
