# Generated by Django 3.0.3 on 2020-02-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
