# Generated by Django 3.0.3 on 2020-02-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20200209_1909'),
        ('contas', '0002_auto_20200208_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceuser',
            name='carrinho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.CarrinhoCompras'),
        ),
    ]
