# Generated by Django 3.0.3 on 2020-02-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20200211_2130'),
        ('contas', '0003_ecommerceuser_carrinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='carrinho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.CarrinhoCompras'),
        ),
    ]
